"""
metadata_generator.py
----------------------
Auto-generates Harvard Dataverse-compliant metadata for a dataset file.

Generation strategy (in priority order):
  1. Groq LLM  (free public API — set GROQ_API_KEY in .env)
     → Generates description, keywords, subject, geographic coverage, time period.
  2. Pure RAG  (sentence-transformers, fully local, zero cost, no API key needed)
     → Fallback when GROQ_API_KEY is not set.

Title rule (always):
  The title is ALWAYS derived from the original filename — never generated by the LLM.
  e.g.  "NO3Field_2024.csv"  →  "NO3Field 2024"

Supports: CSV, TXT, MD

Output is a Python dict ready to POST to the Dataverse Native API.
"""

from __future__ import annotations

import csv
import json
import os
from pathlib import Path
from typing import Dict, Any

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser


DEFAULT_AUTHOR            = os.getenv("DATAVERSE_AUTHOR_NAME", "Unknown Author")
DEFAULT_AUTHOR_AFFILIATION = os.getenv("DATAVERSE_AUTHOR_AFFILIATION", "")
DEFAULT_CONTACT_EMAIL     = os.getenv("DATAVERSE_CONTACT_EMAIL", "")
GROQ_API_KEY              = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL                = os.getenv("GROQ_MODEL", "llama3-70b-8192")


# ---------------------------------------------------------------------------
# Title helper — always from filename, never from LLM
# ---------------------------------------------------------------------------

def title_from_filename(original_filename: str) -> str:
    """Derive a clean title from the original filename.

    Examples:
        NO3Field_2024.csv          → "NO3Field 2024"
        faostat_forestry_data.csv  → "Faostat Forestry Data"
        marine-biomass-survey.csv  → "Marine Biomass Survey"
    """
    stem = Path(original_filename).stem
    clean = stem.replace("_", " ").replace("-", " ").strip()
    return clean.title() if clean.islower() or clean.isupper() else clean


# ---------------------------------------------------------------------------
# File preview extractor (used by both Groq and RAG paths)
# ---------------------------------------------------------------------------

def _extract_preview(file_path: str, max_rows: int = 20) -> str:
    """Extract a text preview of the dataset for the LLM to analyse."""
    path = Path(file_path)

    if path.suffix.lower() == ".csv":
        lines = []
        with open(path, newline="", encoding="utf-8", errors="replace") as f:
            reader = csv.reader(f)
            for i, row in enumerate(reader):
                if i > max_rows:
                    lines.append(f"... ({i} total rows)")
                    break
                lines.append(", ".join(row))
        return "\n".join(lines)

    elif path.suffix.lower() in (".txt", ".md"):
        with open(path, encoding="utf-8", errors="replace") as f:
            return f.read(3000)

    return f"File: {path.name} ({path.suffix})"


# ---------------------------------------------------------------------------
# Groq LLM metadata generation (free)
# ---------------------------------------------------------------------------

METADATA_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are a research data librarian specialising in FAIR data principles \
and Harvard Dataverse metadata standards.

Given a preview of a dataset, generate high-quality metadata for publishing to \
Harvard Dataverse. Return ONLY a valid JSON object with exactly these fields:

{{
  "description": "2-3 sentence abstract describing what the data is, its scope, \
time range, geographic coverage, and source organisation",
  "keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"],
  "subject": "One of: Agricultural Sciences | Arts and Humanities | Astronomy and Astrophysics | Business and Management | Chemistry | Computer and Information Science | Earth and Environmental Sciences | Engineering | Law | Mathematical Sciences | Medicine, Health and Life Sciences | Physics | Social Sciences | Other",
  "geographic_coverage": "Country or region the data covers",
  "time_period_start": "YYYY",
  "time_period_end": "YYYY",
  "data_source": "Name of the originating organisation or database",
  "license": "CC0 1.0",
  "related_publication": ""
}}

Rules:
- Keywords must be domain-relevant and specific
- Subject must be EXACTLY one of the options listed above
- Do not add any text outside the JSON object"""),
    ("human", "Dataset preview:\n\n{preview}\n\nGenerate the metadata JSON."),
])


def _parse_llm_json(raw: str) -> Dict[str, Any]:
    """Robustly parse JSON from LLM output, stripping code fences etc."""
    raw = raw.strip()
    if raw.startswith("```"):
        parts = raw.split("```")
        raw = parts[1] if len(parts) > 1 else raw
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()
    start, end = raw.find("{"), raw.rfind("}") + 1
    if start != -1 and end > start:
        raw = raw[start:end]
    try:
        return json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(
            f"LLM did not return valid JSON. Error: {e}\n"
            f"Raw output (first 400 chars): {raw[:400]}"
        )


def generate_metadata_groq(
    file_path: str,
    original_filename: str = "",
    model: str = GROQ_MODEL,
) -> Dict[str, Any]:
    """Use Groq (free API) to generate metadata — title always from filename.

    Get a free API key at: https://console.groq.com
    Set GROQ_API_KEY in your .env file.
    """
    from langchain_groq import ChatGroq

    title = title_from_filename(original_filename or Path(file_path).name)
    preview = _extract_preview(file_path)

    llm = ChatGroq(model=model, temperature=0.0, api_key=GROQ_API_KEY)
    chain = METADATA_PROMPT | llm | StrOutputParser()
    raw = chain.invoke({"preview": preview})

    generated = _parse_llm_json(raw)
    generated["title"] = title  # Always override with filename-based title

    print(f"[GroqMetadata] Generated metadata for '{title}':")
    for k, v in generated.items():
        print(f"  {k}: {v}")

    return generated


# ---------------------------------------------------------------------------
# Dataverse metadata schema builder
# ---------------------------------------------------------------------------

def build_dataverse_metadata(
    generated: Dict[str, Any],
    author_name: str = DEFAULT_AUTHOR,
    author_affiliation: str = DEFAULT_AUTHOR_AFFILIATION,
    contact_email: str = DEFAULT_CONTACT_EMAIL,
) -> Dict[str, Any]:
    """Convert generated metadata dict into Dataverse Native API schema."""

    fields = [
        {
            "typeName": "title",
            "multiple": False,
            "typeClass": "primitive",
            "value": generated.get("title", "Untitled Dataset"),
        },
        {
            "typeName": "author",
            "multiple": True,
            "typeClass": "compound",
            "value": [
                {
                    "authorName": {
                        "typeName": "authorName",
                        "multiple": False,
                        "typeClass": "primitive",
                        "value": author_name,
                    },
                    "authorAffiliation": {
                        "typeName": "authorAffiliation",
                        "multiple": False,
                        "typeClass": "primitive",
                        "value": author_affiliation,
                    },
                }
            ],
        },
        {
            "typeName": "datasetContact",
            "multiple": True,
            "typeClass": "compound",
            "value": [
                {
                    "datasetContactName": {
                        "typeName": "datasetContactName",
                        "multiple": False,
                        "typeClass": "primitive",
                        "value": author_name,
                    },
                    "datasetContactEmail": {
                        "typeName": "datasetContactEmail",
                        "multiple": False,
                        "typeClass": "primitive",
                        "value": contact_email or "your@email.com",
                    },
                }
            ],
        },
        {
            "typeName": "dsDescription",
            "multiple": True,
            "typeClass": "compound",
            "value": [
                {
                    "dsDescriptionValue": {
                        "typeName": "dsDescriptionValue",
                        "multiple": False,
                        "typeClass": "primitive",
                        "value": generated.get("description", ""),
                    }
                }
            ],
        },
        {
            "typeName": "subject",
            "multiple": True,
            "typeClass": "controlledVocabulary",
            "value": [generated.get("subject", "Earth and Environmental Sciences")],
        },
        {
            "typeName": "keyword",
            "multiple": True,
            "typeClass": "compound",
            "value": [
                {
                    "keywordValue": {
                        "typeName": "keywordValue",
                        "multiple": False,
                        "typeClass": "primitive",
                        "value": kw,
                    }
                }
                for kw in generated.get("keywords", [])
            ],
        },
    ]

    # Time period
    if generated.get("time_period_start") or generated.get("time_period_end"):
        fields.append({
            "typeName": "timePeriodCovered",
            "multiple": True,
            "typeClass": "compound",
            "value": [
                {
                    "timePeriodCoveredStart": {
                        "typeName": "timePeriodCoveredStart",
                        "multiple": False,
                        "typeClass": "primitive",
                        "value": generated.get("time_period_start", ""),
                    },
                    "timePeriodCoveredEnd": {
                        "typeName": "timePeriodCoveredEnd",
                        "multiple": False,
                        "typeClass": "primitive",
                        "value": generated.get("time_period_end", ""),
                    },
                }
            ],
        })

    # Geographic coverage — free text to avoid controlled vocabulary errors
    if generated.get("geographic_coverage"):
        fields.append({
            "typeName": "geographicCoverage",
            "multiple": True,
            "typeClass": "compound",
            "value": [
                {
                    "otherGeographicCoverage": {
                        "typeName": "otherGeographicCoverage",
                        "multiple": False,
                        "typeClass": "primitive",
                        "value": generated.get("geographic_coverage", ""),
                    }
                }
            ],
        })

    # Data source
    if generated.get("data_source"):
        fields.append({
            "typeName": "dataSources",
            "multiple": True,
            "typeClass": "primitive",
            "value": [generated["data_source"]],
        })

    return {
        "datasetVersion": {
            "license": {
                "name": generated.get("license", "CC0 1.0"),
                "uri": "http://creativecommons.org/publicdomain/zero/1.0",
            },
            "metadataBlocks": {
                "citation": {
                    "name": "citation",
                    "fields": fields,
                }
            },
        }
    }


# ---------------------------------------------------------------------------
# Public entry point — auto-selects best available method
# ---------------------------------------------------------------------------

def generate_dataverse_metadata(
    file_path: str,
    author_name: str = DEFAULT_AUTHOR,
    author_affiliation: str = DEFAULT_AUTHOR_AFFILIATION,
    contact_email: str = DEFAULT_CONTACT_EMAIL,
    model: str = GROQ_MODEL,
    use_rag: bool = True,
    original_filename: str = "",
) -> Dict[str, Any]:
    """Generate metadata and build the full Dataverse schema.

    Priority:
      1. Groq LLM   — if GROQ_API_KEY is set in .env  (free, best quality)
      2. RAG        — local sentence-transformers, no API key needed (free, offline)

    Title is ALWAYS taken from the original filename regardless of method.
    """
    title = title_from_filename(original_filename or Path(file_path).name)

    if GROQ_API_KEY:
        print(f"[MetadataGenerator] Using Groq LLM (model: {model})")
        try:
            generated = generate_metadata_groq(file_path, original_filename=original_filename, model=model)
        except Exception as e:
            print(f"[MetadataGenerator] Groq failed ({e}), falling back to RAG.")
            from modules.rag_metadata_generator import generate_metadata_rag
            generated = generate_metadata_rag(file_path, original_filename=original_filename)
    else:
        print("[MetadataGenerator] No GROQ_API_KEY found — using local RAG pipeline.")
        from modules.rag_metadata_generator import generate_metadata_rag
        generated = generate_metadata_rag(file_path, original_filename=original_filename)

    # Always enforce filename-based title
    generated["title"] = title

    return build_dataverse_metadata(generated, author_name, author_affiliation, contact_email)
